// Static country name mappings - generated from m49_regions.csv
// This eliminates the need for runtime database queries since this data is essentially static
export const COUNTRY_NAME_MAPPINGS: Record<string, string> = {
  "DZ": "Algeria",
  "EG": "Egypt",
  "LY": "Libya",
  "MA": "Morocco",
  "SD": "Sudan",
  "TN": "Tunisia",
  "EH": "Western Sahara",
  "IO": "British Indian Ocean Territory",
  "BI": "Burundi",
  "KM": "Comoros",
  "DJ": "Djibouti",
  "ER": "Eritrea",
  "ET": "Ethiopia",
  "TF": "French Southern Territories",
  "KE": "Kenya",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MZ": "Mozambique",
  "RE": "Réunion",
  "RW": "Rwanda",
  "SC": "Seychelles",
  "SO": "Somalia",
  "SS": "South Sudan",
  "UG": "Uganda",
  "TZ": "Tanzania",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "AO": "Angola",
  "CM": "Cameroon",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CG": "Congo",
  "CD": "DR Congo",
  "GQ": "Equatorial Guinea",
  "GA": "Gabon",
  "ST": "Sao Tome and Principe",
  "BW": "Botswana",
  "SZ": "Eswatini",
  "LS": "Lesotho",
  "NA": "Namibia",
  "ZA": "South Africa",
  "BJ": "Benin",
  "BF": "Burkina Faso",
  "CV": "Cabo Verde",
  "CI": "Côte d'Ivoire",
  "GM": "Gambia",
  "GH": "Ghana",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "LR": "Liberia",
  "ML": "Mali",
  "MR": "Mauritania",
  "NE": "Niger",
  "NG": "Nigeria",
  "SH": "Saint Helena",
  "SN": "Senegal",
  "SL": "Sierra Leone",
  "TG": "Togo",
  "AI": "Anguilla",
  "AG": "Antigua and Barbuda",
  "AW": "Aruba",
  "BS": "Bahamas",
  "BB": "Barbados",
  "BQ": "Bonaire, Sint Eustatius and Saba",
  "VG": "British Virgin Islands",
  "KY": "Cayman Islands",
  "CU": "Cuba",
  "CW": "Curaçao",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "HT": "Haiti",
  "JM": "Jamaica",
  "MQ": "Martinique",
  "MS": "Montserrat",
  "PR": "Puerto Rico",
  "BL": "Saint Barthélemy",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin (French Part)",
  "VC": "Saint Vincent and the Grenadines",
  "SX": "Sint Maarten (Dutch part)",
  "TT": "Trinidad and Tobago",
  "TC": "Turks and Caicos Islands",
  "VI": "United States Virgin Islands",
  "BZ": "Belize",
  "CR": "Costa Rica",
  "SV": "El Salvador",
  "GT": "Guatemala",
  "HN": "Honduras",
  "MX": "Mexico",
  "NI": "Nicaragua",
  "PA": "Panama",
  "AR": "Argentina",
  "BO": "Bolivia",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "CL": "Chile",
  "CO": "Colombia",
  "EC": "Ecuador",
  "FK": "Falkland Islands (Malvinas)",
  "GF": "French Guiana",
  "GY": "Guyana",
  "PY": "Paraguay",
  "PE": "Peru",
  "GS": "South Georgia and the South Sandwich Islands",
  "SR": "Suriname",
  "UY": "Uruguay",
  "VE": "Venezuela",
  "BM": "Bermuda",
  "CA": "Canada",
  "GL": "Greenland",
  "PM": "Saint Pierre and Miquelon",
  "US": "United States",
  "AQ": "Antarctica",
  "KZ": "Kazakhstan",
  "KG": "Kyrgyzstan",
  "TJ": "Tajikistan",
  "TM": "Turkmenistan",
  "UZ": "Uzbekistan",
  "CN": "China",
  "HK": "Hong Kong",
  "MO": "Macao",
  "KP": "North Korea",
  "JP": "Japan",
  "MN": "Mongolia",
  "KR": "South Korea",
  "BN": "Brunei Darussalam",
  "KH": "Cambodia",
  "ID": "Indonesia",
  "LA": "Laos",
  "MY": "Malaysia",
  "MM": "Myanmar",
  "PH": "Philippines",
  "SG": "Singapore",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "VN": "Viet Nam",
  "AF": "Afghanistan",
  "BD": "Bangladesh",
  "BT": "Bhutan",
  "IN": "India",
  "IR": "Iran",
  "MV": "Maldives",
  "NP": "Nepal",
  "PK": "Pakistan",
  "LK": "Sri Lanka",
  "AM": "Armenia",
  "AZ": "Azerbaijan",
  "BH": "Bahrain",
  "CY": "Cyprus",
  "GE": "Georgia",
  "IQ": "Iraq",
  "IL": "Israel",
  "JO": "Jordan",
  "KW": "Kuwait",
  "LB": "Lebanon",
  "OM": "Oman",
  "QA": "Qatar",
  "SA": "Saudi Arabia",
  "PS": "State of Palestine",
  "SY": "Syrian Arab Republic",
  "TR": "Türkiye",
  "AE": "United Arab Emirates",
  "YE": "Yemen",
  "BY": "Belarus",
  "BG": "Bulgaria",
  "CZ": "Czechia",
  "HU": "Hungary",
  "PL": "Poland",
  "MD": "Republic of Moldova",
  "RO": "Romania",
  "RU": "Russian Federation",
  "SK": "Slovakia",
  "UA": "Ukraine",
  "AX": "Åland Islands",
  "DK": "Denmark",
  "EE": "Estonia",
  "FO": "Faroe Islands",
  "FI": "Finland",
  "GG": "Guernsey",
  "IS": "Iceland",
  "IE": "Ireland",
  "IM": "Isle of Man",
  "JE": "Jersey",
  "LV": "Latvia",
  "LT": "Lithuania",
  "NO": "Norway",
  "SJ": "Svalbard and Jan Mayen Islands",
  "SE": "Sweden",
  "GB": "United Kingdom",
  "AL": "Albania",
  "AD": "Andorra",
  "BA": "Bosnia and Herzegovina",
  "HR": "Croatia",
  "GI": "Gibraltar",
  "GR": "Greece",
  "VA": "Holy See",
  "IT": "Italy",
  "MT": "Malta",
  "ME": "Montenegro",
  "MK": "North Macedonia",
  "PT": "Portugal",
  "SM": "San Marino",
  "RS": "Serbia",
  "SI": "Slovenia",
  "ES": "Spain",
  "AT": "Austria",
  "BE": "Belgium",
  "FR": "France",
  "DE": "Germany",
  "LI": "Liechtenstein",
  "LU": "Luxembourg",
  "MC": "Monaco",
  "NL": "Netherlands",
  "CH": "Switzerland",
  "AU": "Australia",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "HM": "Heard Island and McDonald Islands",
  "NZ": "New Zealand",
  "NF": "Norfolk Island",
  "FJ": "Fiji",
  "NC": "New Caledonia",
  "PG": "Papua New Guinea",
  "SB": "Solomon Islands",
  "VU": "Vanuatu",
  "GU": "Guam",
  "KI": "Kiribati",
  "MH": "Marshall Islands",
  "FM": "Micronesia",
  "NR": "Nauru",
  "MP": "Northern Mariana Islands",
  "PW": "Palau",
  "UM": "United States Minor Outlying Islands",
  "AS": "American Samoa",
  "CK": "Cook Islands",
  "PF": "French Polynesia",
  "NU": "Niue",
  "PN": "Pitcairn",
  "WS": "Samoa",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TV": "Tuvalu",
  "WF": "Wallis and Futuna Islands"
};

// Helper function to get country name by ISO2 code
export function getCountryName(iso2Code: string): string {
  return COUNTRY_NAME_MAPPINGS[iso2Code] || iso2Code;
}
